const CONFIG = {
    titleWeb: "Tặng quà nè",
    introTitle: 'Xin chào',
    introDesc: `Đây là Công chúa lớn. Hôm nay Công chúa lớn sẽ mang đến cho bạn một món quá đặc biệt nhé ;) `,
    btnIntro: '^^HiHi^^',
    title: 'Hãy chọn cho mình một phần quà nàooooo 🥰',
    btnYes: '+ 1 hoạt động trong kỳ này nhé :33',
    btnNo: '500k <3',
    question: 'Bạn có thích món quà này không?',
    btnReply: 'Yêuuuuu',
    reply: 'Mình thích lắm',
    mess: 'Mình biết bạn sẽ thích món quà này mà 😘😘',
    messDesc: 'Bạn có muốn được nhận thêm quà nữa không?',
    btnAccept: 'Tất nhiên rồii',
}
