const CONFIG = {
    titleWeb: "Tiêu đề web",
    introTitle: 'Xin chào',
    introDesc: `Đây là Công chúa lớn. Hôm nay Công chúa lớn sẽ mang đến cho bạn một món quá đặc biệt nhé ;) `,
    btnIntro: '^^HiHi^^',
    title: 'Hãy chọn cho mình một phần quà nàooooo 🥰',
    btnYes: '+ 1 hoạt động trong kỳ này nhé :33',
    btnNo: '500k <3',
    question: 'Bạn có thích món quà này không? Nếu thích hãy reply"CamonLHN" nhéeee',
    btnReply: 'CamonLHN',
    reply: 'CamonLHN',
    mess: 'Mình biết ban sẽ thích món quà này mà 😘😘',
    messDesc: 'Bạn có thích nhận thêm quà nữa không? Nếu muốn hãy rep "Có chứ" nhé.',
    btnAccept: 'Có chứ',
}
